version: "3.7"

networks:
  wordpress.test:
    name: wordpress.test

services:
  traefik:
    image: "traefik:v2.0.0"
    command:
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--api.insecure"
      - "--api.dashboard"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - wordpress.test

  mysql:
    image: mysql:${LOCAL_MYSQL-latest}
    networks:
      - wordpress.test
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./tools/local-env/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  browserless:
    image: browserless/chrome
    container_name: "browserless"
    networks:
      - wordpress.test
    environment:
      - DEBUG=browserless/chrome
      - MAX_CONCURRENT_SESSIONS=10
      - FUNCTION_EXTERNALS=["lighthouse"]
      - FUNCTION_BUILT_INS=["url"]
    ports:
      - "3000:3000"
    restart: always
    links:
      - wp:wczgz2020.wordpress.test

  wp:
    image: nginx:alpine
    depends_on: ["mysql"]
    networks:
      - wordpress.test
    volumes:
      - ./tools/local-env/default.template:/etc/nginx/conf.d/default.template
      - ./:/var/www
    environment:
      - LOCAL_DIR=${LOCAL_DIR-src}
    labels:
      - "traefik.docker.network=services_wordpress.test"
      - "traefik.http.routers.wp.rule=Host(`wczgz2020.wordpress.test`)"
      - "traefik.http.services.wp.loadbalancer.server.port=80"
    entrypoint: ["sh", "-c"]
    command:
      - |
        envsubst '$$LOCAL_DIR' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'
    depends_on:
      - php
      - traefik

  php:
    image: wordpressdevelop/php:${LOCAL_PHP-latest}
    networks:
      - wordpress.test
    environment:
      LOCAL_PHP_XDEBUG: ${LOCAL_PHP_XDEBUG-false}
      LOCAL_PHP_MEMCACHED: ${LOCAL_PHP_MEMCACHED-false}
      PHP_FPM_UID: ${PHP_FPM_UID-1000}
      PHP_FPM_GID: ${PHP_FPM_GID-1000}
    volumes:
      - ./tools/local-env/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
      - ./:/var/www
    depends_on:
      - mysql

  cli:
    image: wordpressdevelop/cli:${LOCAL_PHP-latest}
    networks:
      - wordpress.test
    environment:
      LOCAL_PHP_XDEBUG: ${LOCAL_PHP_XDEBUG-false}
      LOCAL_PHP_MEMCACHED: ${LOCAL_PHP_MEMCACHED-false}
      PHP_FPM_UID: ${PHP_FPM_UID-1000}
      PHP_FPM_GID: ${PHP_FPM_GID-1000}
    volumes:
      - ./:/var/www
    init: true

  phpunit:
    image: wordpressdevelop/phpunit:${LOCAL_PHP-latest}
    networks:
      - wordpress.test
    environment:
      LOCAL_PHP_XDEBUG: ${LOCAL_PHP_XDEBUG-false}
      LOCAL_PHP_MEMCACHED: ${LOCAL_PHP_MEMCACHED-false}
      LOCAL_DIR: ${LOCAL_DIR-src}
      WP_MULTISITE: ${WP_MULTISITE-false}
      PHP_FPM_UID: ${PHP_FPM_UID-1000}
      PHP_FPM_GID: ${PHP_FPM_GID-1000}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH-false}
      TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST-false}
    volumes:
      - ./tools/local-env/phpunit-config.ini:/usr/local/etc/php/conf.d/phpunit-config.ini
      - ./:/var/www
      - phpunit-uploads:/var/www/${LOCAL_DIR-src}/wp-content/uploads
    init: true
    depends_on:
      - mysql

volumes:
  mysql: {}
  phpunit-uploads: {}
